/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datos;

import javax.swing.JOptionPane;

/**
 *
 * @author Rafael Rosas
 */
public class Citas extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Citas() {
        setTitle("Citas");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnCitaRegistrar = new javax.swing.JButton();
        btnCitaBuscar = new javax.swing.JButton();
        btnCitaBaja = new javax.swing.JButton();
        btnCitaLimpiar = new javax.swing.JButton();
        txtCitaId = new javax.swing.JTextField();
        txtCitaHora = new javax.swing.JTextField();
        btnRegresarCitai = new javax.swing.JButton();
        txtCitaClienteID = new javax.swing.JTextField();
        txtCitaFecha = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setText("ID Cita:");

        jLabel21.setText("Fecha:");

        btnCitaRegistrar.setBackground(new java.awt.Color(255, 255, 102));
        btnCitaRegistrar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnCitaRegistrar.setText("Registrar");
        btnCitaRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaRegistrarActionPerformed(evt);
            }
        });

        btnCitaBuscar.setBackground(new java.awt.Color(255, 255, 102));
        btnCitaBuscar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnCitaBuscar.setText("Buscar");
        btnCitaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaBuscarActionPerformed(evt);
            }
        });

        btnCitaBaja.setBackground(new java.awt.Color(255, 255, 102));
        btnCitaBaja.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnCitaBaja.setText("Baja");
        btnCitaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaBajaActionPerformed(evt);
            }
        });

        btnCitaLimpiar.setBackground(new java.awt.Color(255, 255, 102));
        btnCitaLimpiar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnCitaLimpiar.setText("Limpiar");
        btnCitaLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaLimpiarActionPerformed(evt);
            }
        });

        txtCitaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCitaHoraActionPerformed(evt);
            }
        });

        btnRegresarCitai.setBackground(new java.awt.Color(255, 255, 102));
        btnRegresarCitai.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnRegresarCitai.setText("Regresar");
        btnRegresarCitai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCitaiActionPerformed(evt);
            }
        });

        txtCitaClienteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCitaClienteIDActionPerformed(evt);
            }
        });

        txtCitaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCitaFechaActionPerformed(evt);
            }
        });

        jLabel22.setText("Hora:");

        jLabel23.setText("Cliente ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCitaId, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCitaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCitaClienteID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCitaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCitaRegistrar)
                            .addComponent(btnCitaBaja))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCitaLimpiar)
                            .addComponent(btnCitaBuscar)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnRegresarCitai)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(txtCitaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtCitaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCitaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCitaClienteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCitaRegistrar)
                            .addComponent(btnCitaBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCitaBaja)
                            .addComponent(btnCitaLimpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresarCitai)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel13.setText("CITAS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel13)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCitaRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaRegistrarActionPerformed
      Boolean guardar = true;
        String mensaje = "";
        Integer ciid = Integer.parseInt(txtCitaId.getText());
        String fe= txtCitaFecha.getText();
        String ciho = txtCitaHora.getText();
        Integer cicli = Integer.parseInt(txtCitaClienteID.getText());
        
        
        if (ciid == 0) {
            guardar = false;
            mensaje += "Escribe el numero de cita\n";
        }
        if (fe.length() == 0) {
            guardar = false;
            mensaje += "Escribe la Fecha";
        }
        if (guardar) {
            datosJDBC control = new datosJDBC();
            control.insertCitas(ciid, fe, ciho, cicli);
     
            
        }
        

        
        
    }//GEN-LAST:event_btnCitaRegistrarActionPerformed

    private void txtCitaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCitaHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCitaHoraActionPerformed

    private void btnCitaLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaLimpiarActionPerformed
       txtCitaId.setText("");
        txtCitaFecha.setText("");
       txtCitaHora.setText("");
       txtCitaClienteID.setText("");
    }//GEN-LAST:event_btnCitaLimpiarActionPerformed

    private void btnCitaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaBajaActionPerformed
        datosJDBC sql = new datosJDBC();
        Integer ciid = Integer.parseInt(txtCitaId.getText());
        sql.eliminarCitas(ciid);
       
    }//GEN-LAST:event_btnCitaBajaActionPerformed

    private void btnCitaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaBuscarActionPerformed
       datosJDBC sql = new datosJDBC();
        Integer ciid = Integer.parseInt(txtCitaId.getText());
       sql.buscarCitas(ciid);
       // sql.buscarCodigoDep(txtCitaId.getText());
        
    }//GEN-LAST:event_btnCitaBuscarActionPerformed

    private void btnRegresarCitaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCitaiActionPerformed
         AdminMain  am= new AdminMain ();
      am.setVisible(true);
      dispose();
    }//GEN-LAST:event_btnRegresarCitaiActionPerformed

    private void txtCitaClienteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCitaClienteIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCitaClienteIDActionPerformed

    private void txtCitaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCitaFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCitaFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Citas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCitaBaja;
    private javax.swing.JButton btnCitaBuscar;
    private javax.swing.JButton btnCitaLimpiar;
    private javax.swing.JButton btnCitaRegistrar;
    private javax.swing.JButton btnRegresarCitai;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField txtCitaClienteID;
    private javax.swing.JTextField txtCitaFecha;
    private javax.swing.JTextField txtCitaHora;
    private javax.swing.JTextField txtCitaId;
    // End of variables declaration//GEN-END:variables
}
