/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datos;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author Rafael Rosas
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    
    Border default_border= BorderFactory.createMatteBorder(1, 0, 1, 0,Color.WHITE);
    
    Border yellow_border= BorderFactory.createMatteBorder(1, 0, 1, 0,Color.YELLOW);
    
    
    JLabel[] menuLabels= new JLabel[4]; 
    //arreglo de panels 
    JPanel[] panels= new JPanel[5];
    //arreglo labels mes
  
    
    
    
    public Cliente() {
        setTitle("ATARI CLIENTE");
        initComponents();
        this.setLocationRelativeTo(null);
       //labels del menu
        menuLabels[0]= jLmenuItem1;
        menuLabels[1]= jLmenuItem2;
        menuLabels[2]= jLmenuItem3;
        //menuLabels[3]= jLmenuItem4;
        menuLabels[3]=jLmenuItem5;
        
      
        //paneles de los paneles de submenus
        panels[0]= panel_menu;
        panels[1]= jPanel_calendario;
        panels[2]= jPanel_producto;
        panels[3]= jPanelContacto;
        panels[4]= jPanelAjustes;
        
        
        
        addActionToMenuLabels();
    }
      private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // close this form
        this.dispose();

    }
    public void setLabelBackground(JLabel label){
        for(JLabel menuItem: menuLabels){
          menuItem.setBackground(new Color(46,49,49));
          menuItem.setForeground(Color.white);  
        }                
          label.setBackground(Color.white);
          label.setForeground(Color.blue);
          
        
    }
    
     
    public void showPanel(JPanel panel){
        for(JPanel pnl: panels ){
            pnl.setVisible(false);
        }
        panel.setVisible(true);
    }
   
    
    public void addActionToMenuLabels(){
        
        Component[] components= jPanelmenu.getComponents();
        for(Component component: components){
            if(component instanceof JLabel){
                JLabel label =(JLabel) component;
                label.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                  setLabelBackground(label);
              
                
                  switch (label.getText().trim()){
                      case "Menu":
                          showPanel(panel_menu);
                          break;
                      /*case "Calendario de Citas":
                          showPanel(jPanel_calendario);
                         // jPanel_usuario.setBackground(Color.red);
                          break;*/
                      case "Producto":
                          showPanel(jPanel_producto);
                          break;
                      case "Contacto":
                          showPanel(jPanelContacto);
                          break;
                      case "Ajustes":
                          showPanel(jPanelAjustes);
                          break;
                  }
                  
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
               
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
          
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                 label.setBorder(yellow_border);
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
         label.setBorder(default_border);
                    }
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelmenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLmenuItem2 = new javax.swing.JLabel();
        jLmenuItem3 = new javax.swing.JLabel();
        jLmenuItem1 = new javax.swing.JLabel();
        jLmenuItem5 = new javax.swing.JLabel();
        panel_menu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel_calendario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelMes6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        labelMes10 = new javax.swing.JLabel();
        labelMes9 = new javax.swing.JLabel();
        labelMes8 = new javax.swing.JLabel();
        labelMes5 = new javax.swing.JLabel();
        labelMes4 = new javax.swing.JLabel();
        labelMes1 = new javax.swing.JLabel();
        labelMes2 = new javax.swing.JLabel();
        labelMes3 = new javax.swing.JLabel();
        labelMes7 = new javax.swing.JLabel();
        labelMes11 = new javax.swing.JLabel();
        labelMes12 = new javax.swing.JLabel();
        labelMes13 = new javax.swing.JLabel();
        labelMes14 = new javax.swing.JLabel();
        labelMes15 = new javax.swing.JLabel();
        labelMes16 = new javax.swing.JLabel();
        labelMes17 = new javax.swing.JLabel();
        labelMes18 = new javax.swing.JLabel();
        labelMes19 = new javax.swing.JLabel();
        labelMes20 = new javax.swing.JLabel();
        labelMes21 = new javax.swing.JLabel();
        labelMes23 = new javax.swing.JLabel();
        labelMes25 = new javax.swing.JLabel();
        labelMes22 = new javax.swing.JLabel();
        labelMes24 = new javax.swing.JLabel();
        labelMes26 = new javax.swing.JLabel();
        labelMes27 = new javax.swing.JLabel();
        labelMes28 = new javax.swing.JLabel();
        labelMes29 = new javax.swing.JLabel();
        labelMes30 = new javax.swing.JLabel();
        labelMes31 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        labelMesElegido = new javax.swing.JLabel();
        jPanel_producto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelContacto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelAjustes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnEliminarCliente = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtClienCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelmenu.setBackground(new java.awt.Color(46, 49, 49));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setText("ATARIS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel5)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLmenuItem2.setBackground(new java.awt.Color(46, 49, 49));
        jLmenuItem2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLmenuItem2.setForeground(new java.awt.Color(255, 255, 255));
        jLmenuItem2.setText("Producto");
        jLmenuItem2.setOpaque(true);

        jLmenuItem3.setBackground(new java.awt.Color(46, 49, 49));
        jLmenuItem3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLmenuItem3.setForeground(new java.awt.Color(255, 255, 255));
        jLmenuItem3.setText("Contacto");
        jLmenuItem3.setOpaque(true);

        jLmenuItem1.setBackground(new java.awt.Color(46, 49, 49));
        jLmenuItem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLmenuItem1.setForeground(new java.awt.Color(255, 255, 255));
        jLmenuItem1.setText("Menu");

        jLmenuItem5.setBackground(new java.awt.Color(46, 49, 49));
        jLmenuItem5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLmenuItem5.setForeground(new java.awt.Color(255, 255, 255));
        jLmenuItem5.setText("Ajustes");
        jLmenuItem5.setOpaque(true);

        panel_menu.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setText("Paquetes:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel18.setText("3");

        jLabel19.setText("Disponibles en la tienda.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("Ataris");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("Somos una empresa lider en el mercado\nbuscando la excelencia empresarial y nos \ncomprometemos con nuestro clientes.");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("Somos Una Empresa");

        jLabel22.setText("Socialmente responsable");

        jLabel24.setText("Con la sociedad.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setText("Ventas:");

        jLabel20.setText("+20,000");

        jLabel21.setText("En los ultimos 30 días.");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel20)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jPanel_calendario.setBackground(new java.awt.Color(153, 153, 255));
        jPanel_calendario.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Calendario");

        labelMes6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes6.setText("6");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel39.setText("Lunes");

        jLabel40.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel40.setText("Martes");

        jLabel41.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel41.setText("Miercoles");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel42.setText("Jueves");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel43.setText("Viernes");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel44.setText("Sabado");

        jLabel45.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel45.setText("Domingo");

        labelMes10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes10.setText("10");

        labelMes9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes9.setText("9");

        labelMes8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes8.setText("8");

        labelMes5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes5.setForeground(new java.awt.Color(204, 0, 0));
        labelMes5.setText("5");

        labelMes4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes4.setForeground(new java.awt.Color(255, 0, 0));
        labelMes4.setText("4");

        labelMes1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes1.setForeground(new java.awt.Color(255, 0, 0));
        labelMes1.setText("1");

        labelMes2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes2.setForeground(new java.awt.Color(255, 0, 0));
        labelMes2.setText("2");

        labelMes3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes3.setForeground(new java.awt.Color(255, 0, 0));
        labelMes3.setText("3");

        labelMes7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes7.setText("7");

        labelMes11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes11.setForeground(new java.awt.Color(204, 0, 0));
        labelMes11.setText("11");

        labelMes12.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes12.setForeground(new java.awt.Color(255, 0, 0));
        labelMes12.setText("12");

        labelMes13.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes13.setText("13");

        labelMes14.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes14.setText("14");

        labelMes15.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes15.setText("15");

        labelMes16.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes16.setText("16");

        labelMes17.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes17.setText("17");

        labelMes18.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes18.setForeground(new java.awt.Color(255, 0, 0));
        labelMes18.setText("18");

        labelMes19.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes19.setForeground(new java.awt.Color(255, 0, 0));
        labelMes19.setText("19");

        labelMes20.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes20.setText("20");

        labelMes21.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes21.setText("21");

        labelMes23.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes23.setText("23");

        labelMes25.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes25.setForeground(new java.awt.Color(255, 0, 0));
        labelMes25.setText("25");

        labelMes22.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes22.setText("22");

        labelMes24.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes24.setText("24");

        labelMes26.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes26.setForeground(new java.awt.Color(255, 0, 0));
        labelMes26.setText("26");

        labelMes27.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes27.setText("27");

        labelMes28.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes28.setText("28");

        labelMes29.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes29.setText("29");

        labelMes30.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes30.setText("30");

        labelMes31.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelMes31.setText("31");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Días En Rojo No DISPONIBLES");

        labelMesElegido.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        labelMesElegido.setText("MES:");

        javax.swing.GroupLayout jPanel_calendarioLayout = new javax.swing.GroupLayout(jPanel_calendario);
        jPanel_calendario.setLayout(jPanel_calendarioLayout);
        jPanel_calendarioLayout.setHorizontalGroup(
            jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel39)
                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel41)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel44)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel45)))
                .addGap(0, 178, Short.MAX_VALUE))
            .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_calendarioLayout.createSequentialGroup()
                                        .addComponent(labelMes1)
                                        .addGap(52, 52, 52))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_calendarioLayout.createSequentialGroup()
                                        .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_calendarioLayout.createSequentialGroup()
                                                .addComponent(labelMes6)
                                                .addGap(48, 48, 48))
                                            .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                                                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelMes13)
                                                    .addComponent(labelMes20)
                                                    .addComponent(labelMes27))
                                                .addGap(41, 41, 41)))
                                        .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                                                .addComponent(labelMes14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelMes15))
                                            .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                                                .addComponent(labelMes7)
                                                .addGap(46, 46, 46)
                                                .addComponent(labelMes8))
                                            .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                                                .addComponent(labelMes21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelMes22))
                                            .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                                                .addComponent(labelMes28)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelMes29)))
                                        .addGap(62, 62, 62)))
                                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                                        .addComponent(labelMes2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelMes3))
                                    .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                                        .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelMes16)
                                            .addComponent(labelMes9)
                                            .addComponent(labelMes23)
                                            .addComponent(labelMes30))
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelMes10)
                                            .addComponent(labelMes17)
                                            .addComponent(labelMes24)
                                            .addComponent(labelMes31))))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelMes11)
                                    .addComponent(labelMes4)
                                    .addComponent(labelMes18)
                                    .addComponent(labelMes25))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelMes12)
                                    .addComponent(labelMes5)
                                    .addComponent(labelMes19)
                                    .addComponent(labelMes26)))))
                    .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(labelMesElegido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_calendarioLayout.setVerticalGroup(
            jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_calendarioLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_calendarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMes1)
                            .addComponent(labelMes2)
                            .addComponent(labelMes3)
                            .addComponent(labelMes4)
                            .addComponent(labelMes5))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMes8)
                    .addComponent(labelMes9)
                    .addComponent(labelMes10)
                    .addComponent(labelMes6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMes7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMes11)
                    .addComponent(labelMes12))
                .addGap(18, 18, 18)
                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMes13)
                    .addComponent(labelMes14)
                    .addComponent(labelMes15)
                    .addComponent(labelMes16)
                    .addComponent(labelMes17)
                    .addComponent(labelMes18)
                    .addComponent(labelMes19))
                .addGap(18, 18, 18)
                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMes20)
                    .addComponent(labelMes21)
                    .addComponent(labelMes22)
                    .addComponent(labelMes23)
                    .addComponent(labelMes24)
                    .addComponent(labelMes25)
                    .addComponent(labelMes26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMes27)
                    .addComponent(labelMes28)
                    .addComponent(labelMes29)
                    .addComponent(labelMes30)
                    .addComponent(labelMes31))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(27, 27, 27)
                .addComponent(labelMesElegido)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jPanel_producto.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_producto.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("Paquetes");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel10.setText("Intermedio                 # 2 Precio: $1950 Internet Con Telefonía");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setText("VIP                            # 3 Precio: $2140 Internet con Telefonía Y Televisión");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel12.setText("Básico:                      # 1 Precio: $550 Internet, Con más megas al domiciliar");

        javax.swing.GroupLayout jPanel_productoLayout = new javax.swing.GroupLayout(jPanel_producto);
        jPanel_producto.setLayout(jPanel_productoLayout);
        jPanel_productoLayout.setHorizontalGroup(
            jPanel_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_productoLayout.createSequentialGroup()
                .addGroup(jPanel_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_productoLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2))
                    .addGroup(jPanel_productoLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel_productoLayout.setVerticalGroup(
            jPanel_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_productoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addComponent(jLabel12)
                .addGap(56, 56, 56)
                .addComponent(jLabel10)
                .addGap(52, 52, 52)
                .addComponent(jLabel11)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        jPanelContacto.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setText("Contactanos");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Director General:  Rafael Rodríguez Rosas ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setText("Programador: Luis Omar Rodríguez ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setText("Programador: Rogelio Reyes");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setText("Tecnico: Andres Reyna Garza");

        javax.swing.GroupLayout jPanelContactoLayout = new javax.swing.GroupLayout(jPanelContacto);
        jPanelContacto.setLayout(jPanelContactoLayout);
        jPanelContactoLayout.setHorizontalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactoLayout.createSequentialGroup()
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContactoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addGroup(jPanelContactoLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanelContactoLayout.setVerticalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanelAjustes.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setText("Ajustes");

        jLabel13.setText("¿Deseas Darte de Baja?");

        btnEliminarCliente.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnEliminarCliente.setText("Baja Cliente");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        jLabel33.setText("Introduce tu correo:");

        javax.swing.GroupLayout jPanelAjustesLayout = new javax.swing.GroupLayout(jPanelAjustes);
        jPanelAjustes.setLayout(jPanelAjustesLayout);
        jPanelAjustesLayout.setHorizontalGroup(
            jPanelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjustesLayout.createSequentialGroup()
                .addGroup(jPanelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAjustesLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel4))
                    .addGroup(jPanelAjustesLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel13)
                            .addGroup(jPanelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtClienCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnEliminarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanelAjustesLayout.setVerticalGroup(
            jPanelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjustesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(56, 56, 56)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(txtClienCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarCliente)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelmenuLayout = new javax.swing.GroupLayout(jPanelmenu);
        jPanelmenu.setLayout(jPanelmenuLayout);
        jPanelmenuLayout.setHorizontalGroup(
            jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmenuLayout.createSequentialGroup()
                .addGroup(jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLmenuItem5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLmenuItem3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLmenuItem2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(jLmenuItem1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelmenuLayout.createSequentialGroup()
                    .addGap(0, 459, Short.MAX_VALUE)
                    .addComponent(jPanel_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelmenuLayout.createSequentialGroup()
                    .addGap(0, 433, Short.MAX_VALUE)
                    .addComponent(jPanel_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelmenuLayout.createSequentialGroup()
                    .addGap(0, 397, Short.MAX_VALUE)
                    .addComponent(jPanelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelmenuLayout.createSequentialGroup()
                    .addGap(0, 397, Short.MAX_VALUE)
                    .addComponent(jPanelAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelmenuLayout.setVerticalGroup(
            jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmenuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLmenuItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLmenuItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLmenuItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLmenuItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelAjustes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        //btnEliminarCliente  eliminarClien
        // txtClienId
          
        Boolean guardar = true;
        String mensaje = ""; 
        String cor= txtClienCorreo.getText();
        
         if (guardar) {
            datosJDBC c= new datosJDBC(); 
            c.eliminarClien2(cor);
           
            dispose();
           
            } else {
            JOptionPane.showMessageDialog(null, mensaje);
        }
        
         
       // sql.eliminarDepartamento(txtDepNombre.getText());
        
        
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLmenuItem1;
    private javax.swing.JLabel jLmenuItem2;
    private javax.swing.JLabel jLmenuItem3;
    private javax.swing.JLabel jLmenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelAjustes;
    private javax.swing.JPanel jPanelContacto;
    private javax.swing.JPanel jPanel_calendario;
    private javax.swing.JPanel jPanel_producto;
    private javax.swing.JPanel jPanelmenu;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel labelMes1;
    private javax.swing.JLabel labelMes10;
    private javax.swing.JLabel labelMes11;
    private javax.swing.JLabel labelMes12;
    private javax.swing.JLabel labelMes13;
    private javax.swing.JLabel labelMes14;
    private javax.swing.JLabel labelMes15;
    private javax.swing.JLabel labelMes16;
    private javax.swing.JLabel labelMes17;
    private javax.swing.JLabel labelMes18;
    private javax.swing.JLabel labelMes19;
    private javax.swing.JLabel labelMes2;
    private javax.swing.JLabel labelMes20;
    private javax.swing.JLabel labelMes21;
    private javax.swing.JLabel labelMes22;
    private javax.swing.JLabel labelMes23;
    private javax.swing.JLabel labelMes24;
    private javax.swing.JLabel labelMes25;
    private javax.swing.JLabel labelMes26;
    private javax.swing.JLabel labelMes27;
    private javax.swing.JLabel labelMes28;
    private javax.swing.JLabel labelMes29;
    private javax.swing.JLabel labelMes3;
    private javax.swing.JLabel labelMes30;
    private javax.swing.JLabel labelMes31;
    private javax.swing.JLabel labelMes4;
    private javax.swing.JLabel labelMes5;
    private javax.swing.JLabel labelMes6;
    private javax.swing.JLabel labelMes7;
    private javax.swing.JLabel labelMes8;
    private javax.swing.JLabel labelMes9;
    private javax.swing.JLabel labelMesElegido;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JTextField txtClienCorreo;
    // End of variables declaration//GEN-END:variables
}
