/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datos;

import javax.swing.JOptionPane;

/**
 *
 * @author Rafael Rosas
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Clientes() {
        setTitle("Clientes");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtClienID = new javax.swing.JTextField();
        txtClienApeMa = new javax.swing.JTextField();
        txtClienNom = new javax.swing.JTextField();
        txtClienApePa = new javax.swing.JTextField();
        txtClienDni = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtClienEdad = new javax.swing.JTextField();
        txtClienContra = new javax.swing.JTextField();
        txtClienTel = new javax.swing.JTextField();
        txtClienFechaNac = new javax.swing.JTextField();
        txtClienCorreo = new javax.swing.JTextField();
        btnClienRegistrar = new javax.swing.JButton();
        btnClienBaja = new javax.swing.JButton();
        btnClienBuscar = new javax.swing.JButton();
        btnClienLimpiar = new javax.swing.JButton();
        btnRegresarC = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtClienPaq = new javax.swing.JTextField();
        txtClienDir = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("ID:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Ape. Pat:");

        jLabel5.setText("Ape. Mat:");

        jLabel6.setText("DNI:");

        txtClienID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienIDActionPerformed(evt);
            }
        });

        txtClienApeMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienApeMaActionPerformed(evt);
            }
        });

        txtClienNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienNomActionPerformed(evt);
            }
        });

        txtClienApePa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienApePaActionPerformed(evt);
            }
        });

        txtClienDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienDniActionPerformed(evt);
            }
        });

        jLabel7.setText("Correo:");

        jLabel8.setText("Telefono");

        jLabel9.setText("Fecha Nacimiento:");

        jLabel10.setText("Edad");

        jLabel11.setText("Contraseña:");

        txtClienEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienEdadActionPerformed(evt);
            }
        });

        txtClienContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienContraActionPerformed(evt);
            }
        });

        txtClienTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienTelActionPerformed(evt);
            }
        });

        txtClienFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienFechaNacActionPerformed(evt);
            }
        });

        txtClienCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienCorreoActionPerformed(evt);
            }
        });

        btnClienRegistrar.setBackground(new java.awt.Color(204, 255, 204));
        btnClienRegistrar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnClienRegistrar.setText("Registrar");
        btnClienRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienRegistrarActionPerformed(evt);
            }
        });

        btnClienBaja.setBackground(new java.awt.Color(204, 255, 204));
        btnClienBaja.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnClienBaja.setText("Baja");
        btnClienBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienBajaActionPerformed(evt);
            }
        });

        btnClienBuscar.setBackground(new java.awt.Color(204, 255, 204));
        btnClienBuscar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnClienBuscar.setText("Buscar");
        btnClienBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienBuscarActionPerformed(evt);
            }
        });

        btnClienLimpiar.setBackground(new java.awt.Color(204, 255, 204));
        btnClienLimpiar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnClienLimpiar.setText("Limpiar");
        btnClienLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienLimpiarActionPerformed(evt);
            }
        });

        btnRegresarC.setBackground(new java.awt.Color(204, 255, 204));
        btnRegresarC.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnRegresarC.setText("Regresar");
        btnRegresarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCActionPerformed(evt);
            }
        });

        jLabel12.setText("Dirección:");

        jLabel13.setText("Paquete:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36)
                                .addComponent(txtClienID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClienNom, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClienApeMa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienApePa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienDni, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtClienPaq, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtClienTel, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(txtClienContra, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(txtClienCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(txtClienFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(txtClienDir)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClienBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienRegistrar)
                    .addComponent(btnClienBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienLimpiar)
                    .addComponent(btnRegresarC))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClienID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnClienRegistrar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtClienTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClienNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienBaja)
                    .addComponent(jLabel9)
                    .addComponent(txtClienFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtClienApePa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienBuscar)
                    .addComponent(jLabel7)
                    .addComponent(txtClienCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtClienApeMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClienLimpiar)
                        .addComponent(txtClienContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(txtClienDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresarC))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtClienEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClienPaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("CLIENTES");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienIDActionPerformed

    private void txtClienApeMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienApeMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienApeMaActionPerformed

    private void txtClienNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienNomActionPerformed

    private void txtClienApePaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienApePaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienApePaActionPerformed

    private void txtClienDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienDniActionPerformed

    private void txtClienEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienEdadActionPerformed

    private void txtClienContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienContraActionPerformed

    private void txtClienTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienTelActionPerformed

    private void txtClienFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienFechaNacActionPerformed

    private void txtClienCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienCorreoActionPerformed

    private void btnClienRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienRegistrarActionPerformed
     Boolean guardar = true;
        String mensaje = "";   
        Integer id = Integer.parseInt(txtClienID.getText());
        String nombre = txtClienNom.getText();
        String pat = txtClienApePa.getText();
        String mat = txtClienApeMa.getText();
        String dni = txtClienDni.getText();
        String ed = txtClienEdad.getText();
        String tel =txtClienTel.getText();
        String fec = txtClienFechaNac.getText();
        String cor= txtClienCorreo.getText();
        String con= txtClienContra.getText();
        String dir = txtClienDir.getText();
        String paq= txtClienPaq.getText();
        if (nombre.length() == 0) {
            guardar = false;
            mensaje += "Escriba el nombre\n";
        }
        if (pat.length() == 0) {
            guardar = false;
            mensaje += "Escriba el apellido paterno, por favor\n";
        }
            if (guardar) {
            datosJDBC c= new datosJDBC(); 
            c.insertClien(id, nombre, pat, mat, dni, ed, tel, fec, cor, con, dir, paq);
          // c.insertClien(nombre, pat, mat, dni, ed, tel, fec, cor, con, dir, paq);
            //c.insertClientes(nombre, pat, mat, dni, ed, tel, fec, cor, con, dir, paq);
           //control.insertEmpleados(id, nombre, pat, mat, dni, fecha, sueldo, depa,ed,dir);
            } else {
            JOptionPane.showMessageDialog(null, mensaje);
        }
        
        
    }//GEN-LAST:event_btnClienRegistrarActionPerformed

    private void btnClienBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienBajaActionPerformed
        datosJDBC sql = new datosJDBC();
        sql.eliminarClien(Integer.parseInt(txtClienID.getText()));
     
        
    }//GEN-LAST:event_btnClienBajaActionPerformed

    private void btnClienBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienBuscarActionPerformed
        String nombre = txtClienNom.getText();
        String pat = txtClienApePa.getText();
        String mat = txtClienApeMa.getText();
        datosJDBC sql = new datosJDBC();
        sql.buscarClien(nombre, pat, mat);
        //sql.buscarEmpleado(txtnombreEmpleados.getText(), txtapepateEmpleados.getText(), txtapeMaterEmpleados.getText());
        
    }//GEN-LAST:event_btnClienBuscarActionPerformed

    private void btnClienLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienLimpiarActionPerformed
        txtClienID.setText("");
        txtClienNom.setText("");
        txtClienApePa.setText("");
        txtClienApeMa.setText("");
        txtClienDni.setText("");
        txtClienEdad.setText("");
        txtClienTel.setText("");
        txtClienFechaNac.setText("");
        txtClienCorreo.setText("");
        txtClienContra.setText("");
        txtClienDir.setText("");
        txtClienPaq.setText("");
    }//GEN-LAST:event_btnClienLimpiarActionPerformed

    private void btnRegresarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCActionPerformed
         AdminMain  am= new AdminMain ();
      am.setVisible(true);
      dispose();
        
        
        
    }//GEN-LAST:event_btnRegresarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienBaja;
    private javax.swing.JButton btnClienBuscar;
    private javax.swing.JButton btnClienLimpiar;
    private javax.swing.JButton btnClienRegistrar;
    private javax.swing.JButton btnRegresarC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField txtClienApeMa;
    private javax.swing.JTextField txtClienApePa;
    private javax.swing.JTextField txtClienContra;
    private javax.swing.JTextField txtClienCorreo;
    private javax.swing.JTextField txtClienDir;
    private javax.swing.JTextField txtClienDni;
    private javax.swing.JTextField txtClienEdad;
    private javax.swing.JTextField txtClienFechaNac;
    private javax.swing.JTextField txtClienID;
    private javax.swing.JTextField txtClienNom;
    private javax.swing.JTextField txtClienPaq;
    private javax.swing.JTextField txtClienTel;
    // End of variables declaration//GEN-END:variables
}
